name: Deploy to VPS

on:
  push:
    branches:
      - development

jobs:
  deploy-clone:
    runs-on: ubuntu-latest

    env:
      USER: cicd
      VPS_IP: 134.209.28.40
      GITHUB_TOKEN_FILE: ~/github_token
      #SSH_PRIVATE_KEY: ~/.ssh/id_key  # Generic name for private key

    steps:
      - name: Checkout Code (on GitHub Actions runner)
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_CICD_PRIVATE_KEY }}" > ~/.ssh/id_key
          chmod 600 ~/.ssh/id_key
          echo "StrictHostKeyChecking no" > ~/.ssh/config

      # fails when all ready exist so removed at the end
      - name: Transfer GITHUB_TOKEN to VPS
        run: |
          ssh $USER@$VPS_IP "echo '${{ secrets.GITHUB_TOKEN }}' > $GITHUB_TOKEN_FILE"
 
      - name: Clone Repository on VPS
        run: |
          ssh $USER@$VPS_IP "
            export GITHUB_TOKEN=$(cat $GITHUB_TOKEN_FILE)
            git clone https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ~/deployments/app
          "

      # no need to keep on vps for security reason , also solve the exist issue  
      - name: Delete GITHUB_TOKEN from VPS
        run: |
          ssh $USER@$VPS_IP "rm $GITHUB_TOKEN_FILE"          