name: Deploy to VPS

on:
  push:
    branches:
      - development

jobs:
  deploy-clone:
    runs-on: ubuntu-latest

    env:
      USER: cicd
      VPS_IP: 134.209.28.40
      GITHUB_TOKEN_FILE: ~/github_token
      DEPLOYMENT_DIR: ~/deployments/app

    steps:
      - name: Checkout Code (on GitHub Actions runner)
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure SSH (on GitHub Actions runner)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_CICD_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" > ~/.ssh/config

      - name: Transfer GITHUB_TOKEN to VPS
        run: |
          ssh $USER@$VPS_IP "echo '${{ secrets.GITHUB_TOKEN }}' > $GITHUB_TOKEN_FILE"

      - name: Rename Deployment Directory on VPS
        run: |
          ssh $USER@$VPS_IP "
            if [ -d $DEPLOYMENT_DIR ]; then
              mv $DEPLOYMENT_DIR ${DEPLOYMENT_DIR}_$(date +'%Y%m%d%H%M%S');
            fi
          "

      - name: Clone Repository on VPS
        run: |
          ssh $USER@$VPS_IP "
            export GITHUB_TOKEN=$(cat $GITHUB_TOKEN_FILE)
            git clone https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $DEPLOYMENT_DIR
          "

      - name: Delete GITHUB_TOKEN from VPS
        run: |
          ssh $USER@$VPS_IP "rm $GITHUB_TOKEN_FILE"