name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy-transfer:
    if: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_CICD_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" > ~/.ssh/config

      - name: Transfer Repository to VPS
        run: |
          scp -r ./ user@vps-address:~/deployments/app
          ssh user@vps-address "cd ~/deployments/app && ./deploy_script.sh"
